# Generated by Django 4.0.6 on 2022-07-27 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='save',
        ),
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
