# Generated by Django 4.0.6 on 2022-07-27 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0002_remove_question_save_question_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
