# Generated by Django 4.0.6 on 2022-07-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0005_rename_answered_question_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=80)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Action Game'), (2, 'Fighting Game')])),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='game',
            field=models.ManyToManyField(blank=True, related_name='games', to='question_box.game'),
        ),
    ]
