# Generated by Django 4.0.6 on 2022-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0007_alter_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('Action', 'Action Game'), ('Fighting', 'Fighting Game'), ('Adventure', 'Adventure Game'), ('Idle', 'Idle Game'), ('Puzzle', 'Puzzle Game'), ('Racing', 'Racing Game'), ('Role-Playing', 'Playing Game'), ('Simulation', 'Simulation Game'), ('Sports', 'Sports Game'), ('Strategy', 'Strategy Game')], max_length=12),
        ),
    ]
